### ISSUE TITLE
Run CI Test in GitHub Actions

### ISSUE THREAD

**Issue by lujiajing1126** [Shouqianba-FT/elastic-env-operator#5]
Unit-test failure: https://github.com/Shouqianba-FT/elastic-env-operator/actions/runs/10078107814/job/27862247163
Int-test failure: https://github.com/Shouqianba-FT/elastic-env-operator/actions/runs/10077919867/job/27861581755

**Comment by runkecheng** [comment]
envtest 指定的k8s版本为1.24, 当前envtest库中对etcd就绪的判断不兼容1.24, 升级依赖版本后解决
